name: "Classic Discord Webhook"
description: "This GitHub Action sends simple discord messages for your commits."
branding:
  icon: activity
  color: gray-dark

inputs:
  webhook:
    description: Discord Webhook
    required: true

runs:
  using: "node16"
  main: "src/index.js"
